###
POST http://0.0.0.0:8009/inquire
Content-Type: application/json

{
    "question": "Roll a d20"
}
###
POST http://0.0.0.0:8009/inquire
Content-Type: application/json

{
  "question": "What are the rules for attack rolls?"
}

###
POST http://0.0.0.0:8009/inquire
Content-Type: application/json

{
    "question": "What is the constitution of Ragnar?"
}

###
POST http://0.0.0.0:8009/inquire
Content-Type: application/json

{
    "question": "What is the rule for a perception check?"
}

###
POST http://0.0.0.0:8009/inquire
Content-Type: application/json

{
    "question": "Create a character for player Alice named Dís, a female Dwarf Fighter with these stats: strength 16, dexterity 12, constitution 15, intelligence 10, wisdom 13, charisma 8"
}
